import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import CategoryPicker from "../components/CategoryPicker";
import FeaturedBlogs from "../components/FeaturedBlogs";
import FeaturedProducts from "../components/FeaturedProducts";
import {
  BannerProps,
  FeaturedBlogsProps,
  FeaturedProductsProps,
  PropsHomePage,
} from "../interfaces/Interfaces";

const Home: NextPage<PropsHomePage> = ({
  bannerData,
  featuredProductsData,
  featuredBlogsData,
}) => {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner title={bannerData?.title} preTitle={bannerData?.preTitle} />

      <CategoryPicker />

      <FeaturedProducts featuredProducts={featuredProductsData} />

      <FeaturedBlogs featuredBlogs={featuredBlogsData} />
    </>
  );
};

export const  getServerSideProps:  GetServerSideProps = async () => {
  const bannerRes = await fetch("http://localhost:5001/banner_content");
  const bannerData: BannerProps = await bannerRes.json();

  const featuredProductsRes = await fetch(
    "http://localhost:5001/products/?_limit=4"
  );
  const featuredProductsData: FeaturedProductsProps[] =
    await featuredProductsRes.json();

  const featuredBlogsRes = await fetch("http://localhost:5001/blogs/?_limit=3");
  const featuredBlogsData: FeaturedBlogsProps[] = await featuredBlogsRes.json();
  return {
    props: {
      bannerData,
      featuredProductsData,
      featuredBlogsData,
    },
  };
};

export default Home;
