import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";
import BlogItem from "../../components/BlogItem";
import PageTitle from "../../components/PageTitle";
import { useRouter } from "next/router";
import { BlogPAgeProps } from "../../interfaces/Interfaces";

const Blog: NextPage<BlogPAgeProps> = ({ data }) => {
  const router = useRouter();
  const [searchValue, setSearchValue] = useState("");

  const handleFilterCategoty = (selectedFilter: string) => {
    const currentQuery = router.query;
    const category = currentQuery.category_like as string;

    if (category === selectedFilter) {
      delete currentQuery.category_like;
    } else {
      currentQuery.category_like = selectedFilter;
    }

    router.push({
      pathname: "/blog",
      query: currentQuery,
    });
  };

  const handleSearchFilter = (e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    router.push({
      query: {
        ...router.query,
        q: searchValue,
      },
    });
    setSearchValue("");
  };

  return (
    <>
      <Head>
        <title>Store - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title="Blog" />

      <section className="bg0 p-t-62 p-b-60">
        <div className="container">
          <div className="row">
            <div className="col-md-8 col-lg-9 p-b-80">
              <div className="p-r-45 p-r-0-lg">
                {data && data.length > 0 ? (
                  data.map((blog) => <BlogItem key={blog.id} blogs={blog} />)
                ) : (
                  <p>There are no results with your search.</p>
                )}
              </div>
            </div>

            <div className="col-md-4 col-lg-3 p-b-80">
              <div className="side-menu">
                <form className="bor17 of-hidden pos-relative">
                  <input
                    className="stext-103 cl2 plh4 size-116 p-l-28 p-r-55"
                    type="text"
                    name="search"
                    placeholder="Search"
                    value={searchValue}
                    onChange={(e) => setSearchValue(e.target.value)}
                  />

                  <button
                    className="flex-c-m size-122 ab-t-r fs-18 cl4 hov-cl1 trans-04"
                    onClick={handleSearchFilter}
                  >
                    <i className="zmdi zmdi-search"></i>
                  </button>
                </form>

                <div className="p-t-55">
                  <h4 className="mtext-112 cl2 p-b-33">Categories</h4>

                  <ul>
                    <li className="bor18">
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => handleFilterCategoty("fashion")}
                      >
                        Fashion
                      </button>
                    </li>

                    <li className="bor18">
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => handleFilterCategoty("beauty")}
                      >
                        Beauty
                      </button>
                    </li>

                    <li className="bor18">
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => handleFilterCategoty("streetstyle")}
                      >
                        Street Style
                      </button>
                    </li>

                    <li className="bor18">
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => handleFilterCategoty("lifestyle")}
                      >
                        Life Style
                      </button>
                    </li>

                    <li className="bor18">
                      <button
                        className="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4"
                        onClick={() => handleFilterCategoty("diy")}
                      >
                        DIY & Crafts
                      </button>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const category = query.category_like;
  const searchFilter = query.q;
  let res;
  let data;
  if (category && searchFilter) {
    res = await fetch(
      `http://localhost:5001/blogs?category_like=${category}&q=${searchFilter}`
    );
    data = await res.json();
  } else if (category) {
    res = await fetch(` http://localhost:5001/blogs?category_like=${category}
    `);
    data = await res.json();
  } else if (searchFilter) {
    res = await fetch(`http://localhost:5001/blogs?q=${searchFilter}`);
    data = await res.json();
  } else {
    res = await fetch("http://localhost:5001/blogs");
    data = await res.json();
  }
  return {
    props: {
      data,
    },
  };
};
export default Blog;
